name: digital-wallet

networks:
  digital-wallet-network:

volumes:
  mongodb_data:
  mongodb_config:

services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
      - digital-wallet-network
    volumes:
      - 'mongodb_data:/data/db'
      - 'mongodb_config:/data/configdb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
