name: mongo-cluster

networks:
  mongo-cluster-network:

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
  mongo1-config:
  mongo2-config:
  mongo3-config:

services:
  mongo1:
    image: mongo
    container_name: mongo1
    networks:
      - mongo-cluster-network
    ports:
      - 27017:27017
    volumes:
      - mongo1-data:/data/db
      - mongo1-config:/data/configdb
      - ${PWD}/mongo/rs_key_file:/etc/mongodb/pki/keyFile
    command: mongod --replSet my-rs --bind_ip_all --port 27017 --keyFile /etc/mongodb/pki/keyFile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo2:
    image: mongo
    container_name: mongo2
    networks:
      - mongo-cluster-network
    ports:
      - 27018:27018
    volumes:
      - mongo2-data:/data/db
      - mongo2-config:/data/configdb
      - ${PWD}/mongo/rs_key_file:/etc/mongodb/pki/keyFile
    command: mongod --replSet my-rs --bind_ip_all --port 27018 --keyFile /etc/mongodb/pki/keyFile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo3:
    image: mongo
    container_name: mongo3
    networks:
      - mongo-cluster-network
    ports:
      - 27019:27019
    volumes:
      - mongo3-data:/data/db
      - mongo3-config:/data/configdb
      - ${PWD}/mongo/rs_key_file:/etc/mongodb/pki/keyFile
    command: mongod --replSet my-rs --bind_ip_all --port 27019 --keyFile /etc/mongodb/pki/keyFile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
